version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    labels:
      - "npm"
      - "dependencies"
    schedule:
      interval: "daily"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"

  # Enable version updates for pip
  - package-ecosytem: "pip"
    directory: "/"
    labels:
      - "pip"
      - "dependencies"
    schedule:
      interval: "daily"
