sudo: required
dist: trusty
language: node_js
services:
  - docker
node_js:
- "10"
before_install:
- npm i -g npm
- docker volume create --name=metadata
- docker-compose up -d --build
install:
- npm install --ignore-scripts
- npm install -g codecov
- pip install --user codecov
script:
- npm run lint
- npm run coverage
cache: npm
