sudo: required
dist: trusty
language: node_js
node_js:
- "10"
before_install:
- npm i -g npm
install:
- npm install --ignore-scripts
- npm install -g codecov
script:
- npm run emit
- npm run lint
- npm run coverage
cache: npm
