# start with a base image
FROM postgres:13.2
LABEL maintainer="akmiller01 <Alex Miller, alex.miller@devinit.org>"

# New users
ENV POSTGRES_USER=analyst_ui_user
ENV POSTGRES_PASSWORD=analyst_ui_pass

# Copy custom configs
COPY ./config/pg/postgresql.conf /etc/postgresql/postgresql.conf
COPY ./config/pg/pg_hba.conf /etc/postgresql/pg_hba.conf

RUN chmod 644 /etc/postgresql/postgresql.conf
RUN chmod 644 /etc/postgresql/pg_hba.conf

# Run DB with custom configs copied above
CMD ["-c", "config_file=/etc/postgresql/postgresql.conf"]

# Add initialization script to initdb
ADD ./database_setup/dba.sql /docker-entrypoint-initdb.d/
