# FROM node:9-alpine@sha256:1fbcd77d0eb2af765d24ae4758b5a94b0d55c6002a15a4431d55795a449ebd3d as api-release
FROM node:12-alpine as api-release

RUN mkdir -p /src/ddw-external-api
WORKDIR /src/ddw-external-api

RUN npm install

CMD npm run dev
