version: '3.3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_pg
    volumes:
      - metadata:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/src"
    expose:
      - "80"
    depends_on:
      - db
    environment:
      - S3_KEY
      - S3_SECRET
      - FTSUSER
      - FTSPASS
      - DJANGO_DEV
      - DJANGO_SECRET_KEY
      - CELERY_BROKER_URL=amqp://admin:ddw_analyst_ui@rabbitmq:5672/myvhost
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VIRTUAL_HOST=ddw.devinit.org
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
      - ./ssl:/etc/ssl/
    depends_on:
      - web

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15672:15672
    restart: always

  celery:
    build: .
    command: celery -A ddw_analyst_ui worker -l info
    depends_on:
      - web
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://admin:ddw_analyst_ui@rabbitmq:5672/myvhost

volumes:
  metadata:
    external: true
