version: '3.3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_pg
    volumes:
      - metadata:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/src"
    expose:
      - "80"
    depends_on:
     - db
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - web

volumes:
  metadata:
    external: true
