# start with a base image
FROM postgres:13.2
LABEL maintainer="wakibi <Chris Wakibi, chrisw@devinit.org>"

# New users
ENV POSTGRES_USER=analyst_ui_user
ENV POSTGRES_PASSWORD=analyst_ui_pass


# Add initialization script to initdb
ADD ./database_setup/dba.sql /docker-entrypoint-initdb.d/
