# start with a base image
FROM postgres
LABEL maintainer="akmiller01 <Alex Miller, alex.miller@devinit.org>"

# Add initialization script to initdb
ADD ./database_setup/dba.sql /docker-entrypoint-initdb.d/
