version: '3.3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_pg
    volumes:
      - metadata:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/src"
    expose:
      - "80"
    depends_on:
     - db
     - rabbitmq
    environment:
     - FTSUSER
     - FTSPASS
     - DJANGO_DEV
     - DJANGO_SECRET_KEY
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VIRTUAL_HOST=ddw.devinit.org
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
      - ./ssl:/etc/ssl/
    depends_on:
      - web
  # rabbit message queue
  rabbitmq:
    image: rabbitmq:3.7-alpine

volumes:
  metadata:
    external: true
