# Generated by Django 2.1.7 on 2019-03-07 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_source_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationstep',
            name='query',
        ),
        migrations.AddField(
            model_name='operationstep',
            name='query_func',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationstep',
            name='query_kwargs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationstep',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Source'),
        ),
        migrations.AddField(
            model_name='source',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
