# Generated by Django 2.1.7 on 2019-03-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190307_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Theme'),
        ),
    ]
