# Generated by Django 2.1.7 on 2019-03-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190325_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_query',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
