# Generated by Django 2.1.7 on 2019-03-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190325_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
