# Generated by Django 2.1.7 on 2019-04-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190325_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationstep',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
