# Generated by Django 2.1.7 on 2019-04-09 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190405_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationstep',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Operation'),
        ),
    ]
