# Generated by Django 2.2.10 on 2020-05-18 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20190523_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('script_name', models.TextField()),
                ('enabled', models.BooleanField()),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('repeat', models.BooleanField()),
                ('interval', models.BigIntegerField(blank=True, null=True)),
                ('interval_type', models.CharField(choices=[('min', 'Minutes'), ('sec', 'Seconds'), ('hrs', 'Hours'), ('dys', 'Days'), ('wks', 'Weeks'), ('mnt', 'Months'), ('yrs', 'Years')], max_length=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduledEventRunInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('start_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('p', 'Pending'), ('r', 'Running'), ('c', 'Completed'), ('e', 'Erroed')], max_length=1)),
                ('scheduled_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ScheduledEvent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
