# Generated by Django 2.2.10 on 2020-05-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_scheduledevent_scheduledeventruninstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledevent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='interval_type',
            field=models.CharField(blank=True, choices=[('min', 'Minutes'), ('sec', 'Seconds'), ('hrs', 'Hours'), ('dys', 'Days'), ('wks', 'Weeks'), ('mnt', 'Months'), ('yrs', 'Years')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='scheduledeventruninstance',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('r', 'Running'), ('c', 'Completed'), ('e', 'Erroed')], default='p', max_length=1),
        ),
    ]
