# Generated by Django 2.2.10 on 2020-05-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200518_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='interval_type',
            field=models.CharField(blank=True, choices=[('min', 'Minutes'), ('sec', 'Seconds'), ('hrs', 'Hours'), ('dys', 'Days'), ('wks', 'Weeks'), ('mnt', 'Months'), ('yrs', 'Years')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scheduledeventruninstance',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
