# Generated by Django 2.2.13 on 2020-06-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200601_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledeventruninstance',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('r', 'Running'), ('c', 'Completed'), ('e', 'Errored'), ('s', 'Skipped')], default='p', max_length=1),
        ),
    ]
