# Generated by Django 2.2.13 on 2020-07-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200616_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledeventruninstance',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
