# Generated by Django 2.2.13 on 2020-08-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_scheduledeventruninstance_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcecolumnmap',
            name='alias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
