# Generated by Django 2.2.13 on 2020-08-05 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_sourcecolumnmap_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationDataColumnAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('column_name', models.TextField()),
                ('column_alias', models.TextField()),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Operation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('operation', 'column_name', 'column_alias')},
            },
        ),
    ]
