# Generated by Django 2.2.13 on 2020-08-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_operationdatacolumnalias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationdatacolumnalias',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='operationdatacolumnalias',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='operationdatacolumnalias',
            name='user',
        ),
    ]
