# Generated by Django 2.2.13 on 2020-08-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200810_1112'),
        ('core', '0019_operation_source'),
    ]

    operations = [
    ]
