# Generated by Django 2.2.13 on 2020-08-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_20200812_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='count_rows',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='row_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
