# Generated by Django 2.2.13 on 2020-08-24 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_merge_20200812_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQueryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('frozen_db_table', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('full_query', models.TextField()),
                ('completed', models.CharField(choices=[('p', 'Pending'), ('r', 'Running'), ('c', 'Completed'), ('e', 'Errored')], default='p', max_length=1)),
                ('comment', models.CharField(max_length=200)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Operation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FrozenData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('parent_db_table', models.CharField(max_length=200)),
                ('frozen_db_table', models.CharField(max_length=200)),
                ('completed', models.CharField(choices=[('p', 'Pending'), ('r', 'Running'), ('c', 'Completed'), ('e', 'Errored')], default='p', max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('comment', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
