# Generated by Django 2.2.13 on 2020-08-18 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200818_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='source',
        ),
    ]
