# Generated by Django 2.2.13 on 2020-09-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_frozendata_savedquerydata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedquerydata',
            name='frozen_db_table',
        ),
    ]
