# Generated by Django 2.2.13 on 2020-09-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_savedquerydata_frozen_db_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedquerydata',
            name='saved_query_db_table',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
