# Generated by Django 2.2.13 on 2020-09-18 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200911_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledevent',
            name='alert',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
