# Generated by Django 2.2.13 on 2020-10-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_frozendata_savedquerydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frozendata',
            old_name='completed',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='savedquerydata',
            old_name='completed',
            new_name='status',
        ),
    ]
