# Generated by Django 2.2.13 on 2020-10-20 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20201014_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frozendata',
            old_name='comment',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='savedquerydata',
            old_name='comment',
            new_name='description',
        ),
    ]
