# Generated by Django 2.2.13 on 2020-10-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20201020_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='frozendata',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
