# Generated by Django 2.2.13 on 2020-10-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_frozendata_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedquerydata',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
