# Generated by Django 3.1 on 2021-02-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_savedquerydata_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='alias_creation_status',
            field=models.TextField(choices=[('d', 'Done'), ('p', 'Pending'), ('e', 'Error')], default='d'),
        ),
    ]
