# Generated by Django 3.1 on 2021-03-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_savedquerydata_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='logs',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='operationstep',
            name='logs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
