# Generated by Django 2.2.13 on 2021-01-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_operation_is_sub_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='is_sub_query',
        ),
    ]
