# Generated by Django 3.1 on 2021-03-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20210303_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='logs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
