# Generated by Django 3.1 on 2021-02-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210218_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='alias_creation_status',
            field=models.CharField(blank=True, choices=[('d', 'Done'), ('p', 'Pending'), ('e', 'Error')], default='d', max_length=1),
        ),
    ]
