# Generated by Django 3.1 on 2021-03-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20210226_0751'),
        ('core', '0037_auto_20210303_1618'),
    ]

    operations = [
    ]
