# Generated by Django 3.1 on 2021-03-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_operation_is_sub_query'),
        ('core', '0038_merge_20210304_1858'),
    ]

    operations = [
    ]
