# Generated by Django 3.1 on 2021-03-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_merge_20210304_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='frozendata',
            name='deletion_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='frozendata',
            name='last_accessed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
