# Generated by Django 3.1 on 2021-03-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_merge_20210304_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='is_sub_query',
            field=models.BooleanField(default=False),
        ),
    ]
