# Generated by Django 3.1.8 on 2021-04-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210325_1604'),
        ('core', '0039_merge_20210309_0759'),
    ]

    operations = [
    ]
