# Generated by Django 3.1.8 on 2021-05-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_merge_20210420_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='advanced_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
