# Generated by Django 3.1 on 2021-05-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_merge_20210420_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='is_sub_query',
            field=models.BooleanField(default=False),
        ),
    ]
