# Generated by Django 3.1 on 2021-05-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_merge_20210420_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='estimated_run_time',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
