# Generated by Django 3.1.12 on 2022-01-18 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0041_operation_advanced_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('etl_process', models.CharField(max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operation')),
                ('saved_dataset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.savedquerydata')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
