# Generated by Django 3.2.12 on 2022-03-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_etlquery_etl_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='is_raw',
            field=models.BooleanField(default=False),
        ),
    ]
