# Generated by Django 3.2.13 on 2022-05-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_operation_is_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='last_accessed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='savedquerydata',
            name='last_accessed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
