# Generated by Django 3.2.13 on 2022-06-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20220524_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='frozendata',
            name='renewal_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='renewal_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedquerydata',
            name='renewal_sent',
            field=models.BooleanField(default=False),
        ),
    ]
