# Generated by Django 2.2.13 on 2020-07-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllResourceFlows',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('country_name', models.TextField(blank=True, null=True)),
                ('iso2', models.TextField(blank=True, null=True)),
                ('iso3', models.TextField(blank=True, null=True)),
                ('flow_direction', models.TextField(blank=True, null=True)),
                ('flow_type', models.TextField(blank=True, null=True)),
                ('flow_name', models.TextField(blank=True, null=True)),
                ('value_2016', models.FloatField(blank=True, null=True)),
                ('value_2017', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'all_resource_flows',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cblb',
            fields=[
                ('country_name', models.TextField(blank=True, null=True)),
                ('di_id', models.TextField(primary_key=True, serialize=False)),
                ('iso3', models.TextField(blank=True, null=True)),
                ('cblb', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cblb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrsCurrentIsos',
            fields=[
                ('country_name', models.TextField(primary_key=True, serialize=False)),
                ('country_code', models.BigIntegerField(blank=True, null=True)),
                ('iso3', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crs_current_isos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrsCurrentRegisos',
            fields=[
                ('region_name', models.TextField(primary_key=True, serialize=False)),
                ('region_code', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crs_current_regisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dac1CurrentIsos',
            fields=[
                ('country_name', models.TextField(primary_key=True, serialize=False)),
                ('country_code', models.BigIntegerField(blank=True, null=True)),
                ('iso3', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dac1_current_isos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dac2ACurrentIsos',
            fields=[
                ('country_name', models.TextField(primary_key=True, serialize=False)),
                ('country_code', models.BigIntegerField(blank=True, null=True)),
                ('iso3', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dac2a_current_isos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dac2BCurrentIsos',
            fields=[
                ('country_name', models.TextField(primary_key=True, serialize=False)),
                ('country_code', models.BigIntegerField(blank=True, null=True)),
                ('iso3', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dac2b_current_isos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dac5CurrentIsos',
            fields=[
                ('country_name', models.TextField(primary_key=True, serialize=False)),
                ('country_code', models.BigIntegerField(blank=True, null=True)),
                ('iso3', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dac5_current_isos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DevelopingCountries',
            fields=[
                ('country_name', models.TextField(blank=True, null=True)),
                ('di_id', models.TextField(primary_key=True, serialize=False)),
                ('iso3', models.TextField(blank=True, null=True)),
                ('developing', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'developing_countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiDeflators2016',
            fields=[
                ('di_id', models.TextField(primary_key=True, serialize=False)),
                ('iso3', models.TextField(blank=True, null=True)),
                ('country_name', models.TextField(blank=True, null=True)),
                ('dac_marker', models.FloatField(blank=True, null=True)),
                ('eu_marker', models.FloatField(blank=True, null=True)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'di_deflators_2016',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiDeflators2017',
            fields=[
                ('di_id', models.TextField(primary_key=True, serialize=False)),
                ('iso3', models.TextField(blank=True, null=True)),
                ('country_name', models.TextField(blank=True, null=True)),
                ('dac_marker', models.FloatField(blank=True, null=True)),
                ('eu_marker', models.FloatField(blank=True, null=True)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'di_deflators_2017',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fragility',
            fields=[
                ('country_name', models.TextField(blank=True, null=True)),
                ('di_id', models.TextField(primary_key=True, serialize=False)),
                ('iso3', models.TextField(blank=True, null=True)),
                ('fragile_2018', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fragility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amountusd', models.IntegerField(blank=True, db_column='amountUSD', null=True)),
                ('budgetyear', models.IntegerField(blank=True, db_column='budgetYear', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('flowtype', models.TextField(blank=True, db_column='flowType', null=True)),
                ('newmoney', models.BooleanField(blank=True, db_column='newMoney', null=True)),
                ('originalamount', models.FloatField(blank=True, db_column='originalAmount', null=True)),
                ('originalcurrency', models.TextField(blank=True, db_column='originalCurrency', null=True)),
                ('method', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('boundary', models.TextField(blank=True, null=True)),
                ('onboundary', models.TextField(blank=True, db_column='onBoundary', null=True)),
                ('donor', models.TextField(blank=True, db_column='Donor', null=True)),
                ('source_location_name', models.TextField(blank=True, db_column='source_Location_name', null=True)),
                ('source_iso3', models.TextField(blank=True, null=True)),
                ('source_usageyear_name', models.TextField(blank=True, db_column='source_UsageYear_name', null=True)),
                ('recipient_organization', models.TextField(blank=True, db_column='Recipient.Organization', null=True)),
                ('destination_globalcluster_name', models.TextField(blank=True, db_column='destination_GlobalCluster_name', null=True)),
                ('destination_country', models.TextField(blank=True, db_column='Destination.Country', null=True)),
                ('destination_iso3', models.TextField(blank=True, null=True)),
                ('destination_usageyear_name', models.TextField(blank=True, db_column='destination_UsageYear_name', null=True)),
                ('destination_plan_name', models.TextField(blank=True, db_column='destination_Plan_name', null=True)),
                ('destination_project_name', models.TextField(blank=True, db_column='destination_Project_name', null=True)),
                ('parentflowid', models.IntegerField(blank=True, db_column='parentFlowId', null=True)),
                ('grandbargainearmarkingtype', models.TextField(blank=True, db_column='grandBargainEarmarkingType', null=True)),
                ('source_plan_id', models.TextField(blank=True, db_column='source_Plan_id', null=True)),
                ('source_plan_name', models.TextField(blank=True, db_column='source_Plan_name', null=True)),
                ('destination_cluster_name', models.TextField(blank=True, db_column='destination_Cluster_name', null=True)),
                ('destination_emergency_name', models.TextField(blank=True, db_column='destination_Emergency_name', null=True)),
                ('exchangerate', models.FloatField(blank=True, db_column='exchangeRate', null=True)),
                ('source_emergency_name', models.TextField(blank=True, db_column='source_Emergency_name', null=True)),
                ('source_globalcluster_name', models.TextField(blank=True, db_column='source_GlobalCluster_name', null=True)),
            ],
            options={
                'db_table': 'fts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FtsCodenames',
            fields=[
                ('donor', models.TextField(db_column='Donor', primary_key=True, serialize=False)),
                ('codename', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fts_codenames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FtsDacregion',
            fields=[
                ('donor', models.TextField(db_column='Donor', primary_key=True, serialize=False)),
                ('region', models.TextField(blank=True, db_column='Region', null=True)),
            ],
            options={
                'db_table': 'fts_dacregion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FtsDeflators',
            fields=[
                ('deflatortype', models.TextField(primary_key=True, serialize=False)),
                ('deflators', models.FloatField(blank=True, db_column='Deflators', null=True)),
            ],
            options={
                'db_table': 'fts_deflators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FtsDeliverychannels',
            fields=[
                ('recipient_organization', models.TextField(db_column='Recipient.Organization', primary_key=True, serialize=False)),
                ('deliverychannels', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fts_deliverychannels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FtsDestinationcountryid',
            fields=[
                ('destination_country', models.TextField(db_column='Destination.Country', primary_key=True, serialize=False)),
                ('destinationcountryid', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fts_destinationcountryid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FtsDonorscountryid',
            fields=[
                ('donor', models.TextField(db_column='Donor', primary_key=True, serialize=False)),
                ('donorcountryid', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fts_donorscountryid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FtsIncomegroups',
            fields=[
                ('destinationcountrytype', models.TextField(primary_key=True, serialize=False)),
                ('incomegroups', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fts_incomegroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FtsIsos',
            fields=[
                ('country_name', models.TextField(primary_key=True, serialize=False)),
                ('country_code', models.BigIntegerField(blank=True, null=True)),
                ('iso3', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fts_isos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FtsNgotype',
            fields=[
                ('recipient_organization', models.TextField(db_column='Recipient.Organization', primary_key=True, serialize=False)),
                ('ngotype', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fts_ngotype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FtsOdaeligible',
            fields=[
                ('destination_country', models.TextField(db_column='Destination.Country', primary_key=True, serialize=False)),
                ('odaeligible', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fts_odaeligible',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FtsPrecoded',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amountusd', models.IntegerField(blank=True, db_column='amountUSD', null=True)),
                ('budgetyear', models.IntegerField(blank=True, db_column='budgetYear', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('flowtype', models.TextField(blank=True, db_column='flowType', null=True)),
                ('newmoney', models.BooleanField(blank=True, db_column='newMoney', null=True)),
                ('originalamount', models.FloatField(blank=True, db_column='originalAmount', null=True)),
                ('originalcurrency', models.TextField(blank=True, db_column='originalCurrency', null=True)),
                ('method', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('boundary', models.TextField(blank=True, null=True)),
                ('onboundary', models.TextField(blank=True, db_column='onBoundary', null=True)),
                ('donor', models.TextField(blank=True, db_column='Donor', null=True)),
                ('source_location_name', models.TextField(blank=True, db_column='source_Location_name', null=True)),
                ('source_iso3', models.TextField(blank=True, null=True)),
                ('source_usageyear_name', models.TextField(blank=True, db_column='source_UsageYear_name', null=True)),
                ('recipient_organization', models.TextField(blank=True, db_column='Recipient.Organization', null=True)),
                ('destination_globalcluster_name', models.TextField(blank=True, db_column='destination_GlobalCluster_name', null=True)),
                ('destination_country', models.TextField(blank=True, db_column='Destination.Country', null=True)),
                ('destination_iso3', models.TextField(blank=True, null=True)),
                ('destination_usageyear_name', models.TextField(blank=True, db_column='destination_UsageYear_name', null=True)),
                ('destination_plan_name', models.TextField(blank=True, db_column='destination_Plan_name', null=True)),
                ('destination_project_name', models.TextField(blank=True, db_column='destination_Project_name', null=True)),
                ('parentflowid', models.IntegerField(blank=True, db_column='parentFlowId', null=True)),
                ('grandbargainearmarkingtype', models.TextField(blank=True, db_column='grandBargainEarmarkingType', null=True)),
                ('source_plan_id', models.TextField(blank=True, db_column='source_Plan_id', null=True)),
                ('source_plan_name', models.TextField(blank=True, db_column='source_Plan_name', null=True)),
                ('destination_cluster_name', models.TextField(blank=True, db_column='destination_Cluster_name', null=True)),
                ('destination_emergency_name', models.TextField(blank=True, db_column='destination_Emergency_name', null=True)),
                ('exchangerate', models.FloatField(blank=True, db_column='exchangeRate', null=True)),
                ('source_emergency_name', models.TextField(blank=True, db_column='source_Emergency_name', null=True)),
                ('source_globalcluster_name', models.TextField(blank=True, db_column='source_GlobalCluster_name', null=True)),
                ('codename', models.TextField(blank=True, null=True)),
                ('privatemoney', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, db_column='Region', null=True)),
                ('donorcountryid', models.TextField(blank=True, null=True)),
                ('recipientcodename', models.TextField(blank=True, null=True)),
                ('ngotype', models.TextField(blank=True, null=True)),
                ('deliverychannels', models.TextField(blank=True, null=True)),
                ('recipientcountryid', models.TextField(blank=True, null=True)),
                ('odaeligible', models.TextField(blank=True, null=True)),
                ('destinationcountryid', models.TextField(blank=True, null=True)),
                ('incomegroups', models.TextField(blank=True, null=True)),
                ('domesticresponse', models.BooleanField(blank=True, null=True)),
                ('deflators', models.FloatField(blank=True, db_column='Deflators', null=True)),
                ('amountdeflated', models.FloatField(blank=True, db_column='amountDeflated', null=True)),
                ('amountdeflatedmillions', models.FloatField(blank=True, db_column='amountDeflatedMillions', null=True)),
            ],
            options={
                'db_table': 'fts_precoded',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FtsPrivatemoney',
            fields=[
                ('donor', models.TextField(db_column='Donor', primary_key=True, serialize=False)),
                ('privatemoney', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fts_privatemoney',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FtsRecipientcodename',
            fields=[
                ('recipient_organization', models.TextField(db_column='Recipient.Organization', primary_key=True, serialize=False)),
                ('recipientcodename', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fts_recipientcodename',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FtsRecipientcountryid',
            fields=[
                ('recipient_organization', models.TextField(db_column='Recipient.Organization', primary_key=True, serialize=False)),
                ('recipientcountryid', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fts_recipientcountryid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalIncomeGroupings',
            fields=[
                ('country_name', models.TextField(blank=True, null=True)),
                ('di_id', models.TextField(primary_key=True, serialize=False)),
                ('iso3', models.TextField(blank=True, null=True)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('income_group', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historical_income_groupings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ldcs',
            fields=[
                ('country_name', models.TextField(blank=True, null=True)),
                ('di_id', models.TextField(primary_key=True, serialize=False)),
                ('iso3', models.TextField(blank=True, null=True)),
                ('ldc', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ldcs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NonGrantRevenue',
            fields=[
                ('di_id', models.TextField(primary_key=True, serialize=False)),
                ('iso3', models.TextField(blank=True, null=True)),
                ('country_name', models.TextField(blank=True, null=True)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('budget_type', models.TextField(blank=True, null=True)),
                ('l2', models.TextField(blank=True, null=True)),
                ('value_current_ncu', models.FloatField(blank=True, null=True)),
                ('value_current_usd', models.FloatField(blank=True, null=True)),
                ('value_usd_constant_2016', models.FloatField(blank=True, null=True)),
                ('value_usd_constant_2017', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'non_grant_revenue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OecdCrsAidTypeRef',
            fields=[
                ('aid_type_code', models.TextField(primary_key=True, serialize=False)),
                ('aid_type_parent_code', models.TextField(blank=True, null=True)),
                ('aid_type_parent_name', models.TextField(blank=True, null=True)),
                ('aid_type_name', models.TextField(blank=True, null=True)),
                ('aid_type_description', models.TextField(blank=True, null=True)),
                ('aid_type_di_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oecd_crs_aid_type_ref',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OecdCrsChannelMap',
            fields=[
                ('channel_parent_category_code', models.BigIntegerField(blank=True, null=True)),
                ('channel_id_code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('year_added', models.FloatField(blank=True, null=True)),
                ('acronym_eng', models.TextField(blank=True, null=True)),
                ('oecd_channel_name', models.TextField(blank=True, null=True)),
                ('oecd_channel_parent_name', models.TextField(blank=True, null=True)),
                ('oecd_aggregated_channel', models.TextField(blank=True, null=True)),
                ('coefficient_for_core_contributions', models.TextField(blank=True, null=True)),
                ('general_contributions_reported_as_type_of_aid', models.TextField(blank=True, null=True)),
                ('mcd_major_channel_of_delivery', models.TextField(blank=True, null=True)),
                ('references_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oecd_crs_channel_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OecdCrsDonorTypeRef',
            fields=[
                ('donor_code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('donor_name', models.TextField(blank=True, null=True)),
                ('donor_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oecd_crs_donor_type_ref',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OecdCrsSectorItepMap',
            fields=[
                ('oecd_sector_code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('oecd_sector_name', models.TextField(blank=True, null=True)),
                ('itep_sector', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oecd_crs_sector_itep_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OecdRegions',
            fields=[
                ('country_name', models.TextField(blank=True, null=True)),
                ('di_id', models.TextField(primary_key=True, serialize=False)),
                ('iso3', models.TextField(blank=True, null=True)),
                ('region_name', models.TextField(blank=True, null=True)),
                ('region_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oecd_regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PovcalnetaggRegisos',
            fields=[
                ('region_name', models.TextField(primary_key=True, serialize=False)),
                ('region_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PovCalNetAgg_regisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PovcalnetdistIsos',
            fields=[
                ('country_name', models.FloatField(primary_key=True, serialize=False)),
                ('country_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PovCalNetDist_isos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Povcalnetp20Isos',
            fields=[
                ('country_name', models.TextField(primary_key=True, serialize=False)),
                ('country_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PovCalNetP20_isos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Povcalnetp20Regisos',
            fields=[
                ('region_name', models.FloatField(primary_key=True, serialize=False)),
                ('region_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PovCalNetP20_regisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PovcalnetsmyIsos',
            fields=[
                ('country_name', models.TextField(primary_key=True, serialize=False)),
                ('country_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PovCalNetSmy_isos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PovcalnetsmyRegisos',
            fields=[
                ('region_name', models.FloatField(primary_key=True, serialize=False)),
                ('region_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PovCalNetSmy_regisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WdiIsos',
            fields=[
                ('country_name', models.TextField(blank=True, null=True)),
                ('country_code', models.TextField(primary_key=True, serialize=False)),
                ('iso3', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wdi_isos',
                'managed': False,
            },
        ),
    ]
