# Generated by Django 3.2.12 on 2022-02-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='global_query',
            field=models.BooleanField(default=False),
        ),
    ]
