# Generated by Django 3.2.12 on 2022-03-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0002_preference_global_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='global_query',
            new_name='global_choice',
        ),
        migrations.AlterField(
            model_name='preference',
            name='preferences',
            field=models.JSONField(blank=True, default={'queryBuilder': 'advanced'}, null=True),
        ),
    ]
