# Generated by Django 3.2.12 on 2022-03-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0003_auto_20220306_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='preferences',
            field=models.JSONField(blank=True, default={'queryBuilder': 'advanced'}),
        ),
    ]
