# Generated by Django 3.2.12 on 2022-03-07 10:18

from django.db import migrations, models
import preference.models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0005_alter_preference_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='preferences',
            field=models.JSONField(blank=True, default=preference.models.default_value, null=True),
        ),
    ]
