import config from '../config';

export const api = {
  routes: {
    LOGIN: `${config.BASE_URL}/api/auth/login/`,
    LOGOUT: `${config.BASE_URL}/api/auth/logout/`,
    USERS: `${config.BASE_URL}/api/users/`,
    SOURCES: `${config.BASE_URL}/api/sources/`,
    DATASETS: `${config.BASE_URL}/api/datasets/`,
    MY_DATASETS: `${config.BASE_URL}/api/datasets/mine/`,
    FETCH_DATASET_HISTORY: `${config.BASE_URL}/api/dataset/history/`,
    SINGLE_DATASET: `${config.BASE_URL}/api/dataset/`,
    DATASET_ALIAS: `${config.BASE_URL}/api/dataset/alias/`,
    PREVIEW_SINGLE_DATASET: `${config.BASE_URL}/api/dataset/preview/`,
    EXPORT: `${config.BASE_URL}/api/export/`,
    CHANGE_PASSWORD: `${config.BASE_URL}/api/change_password/`,
    VIEW_SCHEDULED_EVENTS: `${config.BASE_URL}/api/scheduled_event/`,
    FETCH_RUN_INSTANCES: `${config.BASE_URL}/api/scheduled_event/{id}/run_instances/`,
    CREATE_SCHEDULED_INSTANCE: `${config.BASE_URL}/api/scheduled_event/{scheduleId}/run_instances/`,
    UPDATE_TABLE: `${config.BASE_URL}/api/tables/update/`,
    DOWNLOAD_TABLE: `${config.BASE_URL}/api/tables/download/`,
    FETCH_SOURCE_DATASETS: `${config.BASE_URL}/api/source/datasets/`,
    FETCH_MY_SOURCE_DATASETS: `${config.BASE_URL}/api/source/datasets/mine/`,
    FETCH_SOURCE_HISTORY: `${config.BASE_URL}/api/source/history/`,
    FROZEN_DATA: `${config.BASE_URL}/api/frozendata/`,
    DOWNLOAD_FROZEN_DATA: `${config.BASE_URL}/api/tables/download/{table}/archives/`,
    SAVED_QUERYSETS: `${config.BASE_URL}/api/savedquerysets/`,
    SINGLE_SAVED_QUERYSET: `${config.BASE_URL}/api/savedqueryset/`,
    DOWNLOAD_SAVED_QUERYSET: `${config.BASE_URL}/api/tables/download/{table}/dataset/`,
    FETCH_OPERATION: `${config.BASE_URL}/api/operations/{id}`,
    DATASET_QUERY: `${config.BASE_URL}/api/dataset/query/`,
  },
};
